# Lesson 2

## Review

* What's Classification and Regression?
* Name types of machine learning algorithm.
    * Provide example and a use case for each of them
* What's Perceptron?
* What's Activation Function? Name a few.
    * Explain why we use it?
* What's Loss Function?
* What's Gradient Descent? Why we use it?

### **Exercise**

Import pandas, numpy and matplotlib and make sure your plots are shown in the notebook

In [5]:
# Enter your code here


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Gradient Descent

Is a multi-dimensional **optimization** algorithm with the objective of reaching *global minima*

<a href = 'https://yihui.name/animation/example/grad-desc/'>A visualization</a>

## Broadcasting

The term broadcasting describes how arrays with different shapes are treated during arithmetic operations. The term broadcasting was first used by Numpy, although is now used in other libraries such as Tensorflow and Matlab; the rules can vary by library.

From the Numpy Documentation:

    Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. The simplest example of broadcasting occurs when multiplying an array by a scalar.
    
    
(<a href = 'https://github.com/fastai/numerical-linear-algebra/blob/master/nbs/4.%20Compressed%20Sensing%20of%20CT%20Scans%20with%20Robust%20Regression.ipynb'>Sources</a>)
(<a href = 'https://www.oreilly.com/library/view/python-for-data/9781449323592/ch04.html'>Further Reading</a>)

In [9]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [10]:
v = np.array([1,2,3])
print(v, v.shape)

[1 2 3] (3,)


In [11]:
m = np.array([v,v*2,v*3]); m, m.shape

(array([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]]), (3, 3))

In [15]:
n = np.array([m*2, m*5]); n

(array([[[ 2,  4,  6],
         [ 4,  8, 12],
         [ 6, 12, 18]],
 
        [[ 5, 10, 15],
         [10, 20, 30],
         [15, 30, 45]]]), (2, 3, 3))

we can use broadcasting to add *arrays* and *matrices*

In [16]:
m.shape, n.shape

((3, 3), (2, 3, 3))

In [13]:
m + v

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

notice what happens when we tranpose the array

In [17]:
v1 = np.expand_dims(v, -1); v1, v1.shape

(array([[1],
        [2],
        [3]]), (3, 1))

**Exercise**
Find another way to expand dims

In [ ]:
# Enter your code here


In [22]:
m+v1

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])


**General Numpy Broadcasting Rules**
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the *trailing* dimensions, and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1


Arrays do not need to have the same number of dimensions. For example, if you have a $256 \times 256 \times 3$ array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible:

    Image  (3d array): 256 x 256 x 3
    Scale  (1d array):             3
    Result (3d array): 256 x 256 x 3


**Review**

In [23]:
v = np.array([1,2,3,4])
m = np.array([v,v*2,v*3])
A = np.array([5*m, -1*m])

In [24]:
v.shape, m.shape, A.shape

((4,), (3, 4), (2, 3, 4))

Will the following operations work?

In [ ]:
A

In [ ]:
A + v

In [ ]:
A

In [ ]:
A.T

In [ ]:
A.T.shape, m.shape

In [ ]:
A.T + m

In [21]:
v2 = v[...,np.newaxis]; v2

array([[1],
       [2],
       [3]])

## CNNs

**Review**
* What's overfitting?